apiVersion: v1
kind: PersistentVolume
metadata:
  name: Pv-Name
spec:
  capacity:
    storage: Size of pv(ex.5Gi) 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: The path that is exported by the NFS serve (ex. /nfs)
    server: The host name or IP address of the NFS server (ex. unati.example.com)
  persistentVolumeReclaimPolicy: Recycle 
